language: c

os:
  - linux

compiler:
  - gcc

before_install:
  # gcc 4.8.1
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq

install:
  - sudo apt-get install -qq gnulib
  # gcc 4.8.1
  - sudo apt-get install -qq g++-4.8
  # OpenGL
  - sudo apt-get install freeglut3-dev
  - export CC="gcc-4.8"
  - export CXX="g++-4.8"

before_script:
  - autoreconf -i -I/usr/share/gnulib/m4 -I `pwd`/m4

script:
  - ./configure && make

branches:
  only:
    - master

notifications:
  email:
    - newserver002@gmail.com