language: c
os:
  - linux
  - osx

compiler:
  - clang

install:
  - echo $TRAVIS_OS_NAME
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo apt-get install -qq gnulib; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo apt-get install freeglut3-dev; fi
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then brew install gsed automake autoconf libtool wxmac freeglut; fi 
  - export CC="clang"
  - export CXX="clang++"

before_script:
  - autoreconf -i -I/usr/share/gnulib/m4 -I `pwd`/m4

script:
  - ./configure && make

branches:
  only:
    - master

notifications:
  email:
    - newserver002@gmail.com