language: c

os:
  - linux

compiler:
  - gcc

before_install:
  # gcc 4.8.1
  - if [ "$CXX" == "gcc" ]; then sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test; fi
  - sudo apt-get update -qq

install:
  - sudo apt-get install -qq gnulib
  # gcc 4.8.1
  - if [ "$CC" = "gcc" ]; then sudo apt-get install -qq gcc-4.8; fi
  - if [ "$CC" = "gcc" ]; then export CXX="gcc-4.8"; fi
  # OpenGL
  - sudo apt-get install freeglut3-dev

before_script:
  - autoreconf -i -I/usr/share/gnulib/m4 -I `pwd`/m4

script:
  - ./configure && make

branches:
  only:
    - master

notifications:
  email:
    - newserver002@gmail.com